### ISSUE TITLE
Montar hook para fazer requisições com Axios

### ISSUE THREAD

**Issue by lucas-ifsp** [pet-ads/systematic-front#63]
Ver código no ctruco-front

**Comment by F-Guedes2003** [comment]
A requisição para registrar o usuário está pronta, mas está dando erro no CORS, consegue me ajudar amanhã @gabrmanh pra gente resolver isso?

**Comment by gabrmanh** [comment]
@F-Guedes2003 ajudo sim! 

uma sugestão inicial é: a main não tem o cors configurado ainda. se vc estiver usando ela, tenta baixar a branch cors-config-gabriel do back e rodar nela

se n funfar, só me chamar e amanhã mexemos

**Comment by F-Guedes2003** [comment]
beleza, vou tentar aqui e te aviso, valeu

**Comment by F-Guedes2003** [comment]
bom dia, tudo blz? Mn, ta dando o mesmo erro ainda :/

**Comment by F-Guedes2003** [comment]
Se tu quiser fazer uma call pra gente tentar ajeitar isso, cê me fala
